In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\Cleaned Datasets\gurgaon_properties.csv")

In [3]:
df.sample(5)

,property_name,property_type,society,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2609,2 BHK Flat in Sector 95 Gurgaon,flat,awho shanti vihar,0.80,8888.0,900.0,Super Built up area 900(83.61 sq.m.)Carpet are...,2,2,3,study room,"Sector 95 Gurgaon, Gurgaon, Haryana",9.0,East,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Excellant property in low floor,NaN,"['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction5 out of..."
608,3 BHK Flat in Sector 82A Gurgaon,flat,dlf the primus,2.20,10516.0,2092.0,Super Built up area 2092(194.35 sq.m.),3,3,3+,servant room,"16th Floor Dlf Primus-Sector-82a Gurgaon, Sect...",16.0,North-East,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...",Urgent sale call for more details.\nThis 3 bhk...,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
335,3 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,1.30,9135.0,1423.0,Carpet area: 1423 (132.2 sq.m.),3,3,2,study room,"Sector 89 Gurgaon, Gurgaon, Haryana",2.0,NaN,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",We are the proud owners of this 3 bhk apartmen...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
448,3 BHK Flat in Sector 92 Gurgaon,flat,gls avenue 51,0.50,7812.0,640.0,Carpet area: 640 (59.46 sq.m.),3,3,1,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",Top floor with beautiful view and ample sunlig...,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
427,2 Bedroom House for sale in Ravi Nagar,house,independent,0.35,9722.0,360.0,Plot area 40(33.45 sq.m.),2,2,1,not available,"Ravi Nagar, Gurgaon, Haryana",2.0,South-East,10+ Year Old,NaN,It is an old construction. 1 room set on each ...,NaN,NaN,NaN

In [4]:
df.shape

(3960, 20)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

property_name               0
property_type               0
society                     1
price                      19
price_per_square_feet      19
area                       19
areaWithType                0
bedRoom                     0
bathroom                    0
balcony                     0
additionalRoom              0
address                    11
floorNum                   21
facing                   1177
agePossession               1
nearbyLocations           207
description                 0
furnishDetails           1031
features                  709
rating                    449
dtype: int64

In [7]:
df.head()

,property_name,property_type,society,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 102 Gurgaon,flat,rof aalayas,0.45,6000.0,750.0,Built Up area: 750 (69.68 sq.m.),1,1,2,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['HUDA Metro Station', 'Idea Cosmic Plaza', 'G...","1 bath, semi-Furnished, 6th floor (Of 17), ove...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Construction4 out of..."
1,5 Bedroom House for sale in Sector 56 Gurgaon,house,huda sector-56 gurgaon,3.60,24845.0,1449.0,Plot area 161(134.62 sq.m.),5,5,3+,others,"265, Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Iffco chowk metro station', 'Mg road metro s...","161 yard 2 5 story built up house ,nearby mark...","['10 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'N...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,4 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,2.50,12820.0,1950.0,Carpet area: 1950 (181.16 sq.m.),4,5,3,others,"Sector 48 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Corner 3 side park facing with big covered par...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '25 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,1.35,8181.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Gurgaon greens is a spectacular property place...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Connectivity4 out of 5', 'Management5 out of..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,0.65,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."

In [8]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [9]:
df.head()

,property_name,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 102 Gurgaon,flat,rof aalayas,Sector 102,0.45,6000.0,750.0,Built Up area: 750 (69.68 sq.m.),1,1,...,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['HUDA Metro Station', 'Idea Cosmic Plaza', 'G...","1 bath, semi-Furnished, 6th floor (Of 17), ove...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Construction4 out of..."
1,5 Bedroom House for sale in Sector 56 Gurgaon,house,huda sector-56 gurgaon,Sector 56,3.60,24845.0,1449.0,Plot area 161(134.62 sq.m.),5,5,...,others,"265, Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Iffco chowk metro station', 'Mg road metro s...","161 yard 2 5 story built up house ,nearby mark...","['10 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'N...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,4 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,Sector 48,2.50,12820.0,1950.0,Carpet area: 1950 (181.16 sq.m.),4,5,...,others,"Sector 48 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Corner 3 side park facing with big covered par...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '25 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,Sector 102,1.35,8181.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,...,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Gurgaon greens is a spectacular property place...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Connectivity4 out of 5', 'Management5 out of..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,Sector 92,0.65,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,...,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."

In [10]:
df['sector'] = df['sector'].str.lower()

In [11]:
df.head()

,property_name,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 102 Gurgaon,flat,rof aalayas,sector 102,0.45,6000.0,750.0,Built Up area: 750 (69.68 sq.m.),1,1,...,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['HUDA Metro Station', 'Idea Cosmic Plaza', 'G...","1 bath, semi-Furnished, 6th floor (Of 17), ove...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Construction4 out of..."
1,5 Bedroom House for sale in Sector 56 Gurgaon,house,huda sector-56 gurgaon,sector 56,3.60,24845.0,1449.0,Plot area 161(134.62 sq.m.),5,5,...,others,"265, Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Iffco chowk metro station', 'Mg road metro s...","161 yard 2 5 story built up house ,nearby mark...","['10 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'N...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,4 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,sector 48,2.50,12820.0,1950.0,Carpet area: 1950 (181.16 sq.m.),4,5,...,others,"Sector 48 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Corner 3 side park facing with big covered par...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '25 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,sector 102,1.35,8181.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,...,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Gurgaon greens is a spectacular property place...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Connectivity4 out of 5', 'Management5 out of..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,sector 92,0.65,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,...,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."

In [12]:
df['sector'].value_counts()

sector
sohna                                      163
sector 102                                 113
sector 85                                  110
sector 92                                  104
sector 69                                   94
                                          ...
hsiidc plot sector 1 imt manesar             1
begampur khatola                             1
om nagar                                     1
block h ashok vihar phase iii extension      1
near nand hospital                           1
Name: count, Length: 301, dtype: int64

**I need the exact Sector Information for my analysis.So lets extract sector information from the dataset**

In [13]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [14]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [15]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [16]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [17]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [18]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [19]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [20]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [21]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [22]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
250,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,...,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1110,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1384,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3777,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [23]:
df.loc[250,'sector'] = 'sector 90'
df.loc[1110,'sector'] = 'sector 92'
df.loc[1384,'sector'] = 'sector 37'
df.loc[3777,'sector'] = 'sector 76'

In [24]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
726,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1251,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,...,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2498,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,...,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2870,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3422,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [25]:
df.loc[[726,1251,2498,2870,3422],'sector'] = 'sector 110'

In [27]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]

In [29]:
df = df[df['sector'].isin(a.index)]

In [31]:
df.head()

,property_name,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 102 Gurgaon,flat,rof aalayas,sector 102,0.45,6000.0,750.0,Built Up area: 750 (69.68 sq.m.),1,1,...,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['HUDA Metro Station', 'Idea Cosmic Plaza', 'G...","1 bath, semi-Furnished, 6th floor (Of 17), ove...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Construction4 out of..."
1,5 Bedroom House for sale in Sector 56 Gurgaon,house,huda sector-56 gurgaon,sector 56,3.60,24845.0,1449.0,Plot area 161(134.62 sq.m.),5,5,...,others,"265, Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Iffco chowk metro station', 'Mg road metro s...","161 yard 2 5 story built up house ,nearby mark...","['10 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'N...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,4 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,sector 48,2.50,12820.0,1950.0,Carpet area: 1950 (181.16 sq.m.),4,5,...,others,"Sector 48 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Corner 3 side park facing with big covered par...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '25 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,sector 102,1.35,8181.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,...,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Gurgaon greens is a spectacular property place...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Connectivity4 out of 5', 'Management5 out of..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,sector 92,0.65,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,...,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."

In [32]:
df.shape

(3801, 21)

In [33]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [34]:
df.sample(5)

,property_type,society,sector,price,price_per_square_feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
79,flat,signature global the millennia,sector 37d,0.55,9166.0,600.0,Super Built up area 600(55.74 sq.m.),2,2,3,not available,3.0,NaN,0 to 1 Year Old,"['Jharsha Chowk', 'Hero Honda Chowk', 'Rajiv C...",[],NaN
1049,flat,aipl zen residences,sector 70a,1.82,10996.0,1655.0,Super Built up area 1655(153.75 sq.m.)Built Up...,3,3,3,not available,12.0,South,1 to 5 Year Old,"['Airia Mall', 'National Highway 8', 'Southern...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2563,flat,umang winter hills,sector 77,1.40,6340.0,2208.0,Built Up area: 1735 (161.19 sq.m.),3,3,3,not available,10.0,North-East,undefined,"['Entertainland Mall', 'Delhi Jaipur Expresswa...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Lift(s)', 'Maintenance Staff', 'Water Storag..."
1825,house,housing board colony,sector 28,5.50,30556.0,1800.0,Plot area 200(167.23 sq.m.),4,3,3,"pooja room,others",2.0,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","['1 Exhaust Fan', '1 Chimney', '1 Modular Kitc...","['Water Storage', 'Park', 'Rain Water Harvesti..."
6,flat,experion the heartsong,sector 108,1.65,8237.0,2003.0,Super Built up area 2003(186.08 sq.m.)Built Up...,3,4,3,study room,3.0,North-West,5 to 10 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...","['6 Fan', '6 Light', '4 AC', '1 Modular Kitche...","['Security / Fire Alarm', 'Power Back-up', 'In..."

In [35]:
df.duplicated().sum()

np.int64(122)

In [36]:
df.isnull().sum()

property_type               0
society                     1
sector                      0
price                      17
price_per_square_feet      17
area                       17
areaWithType                0
bedRoom                     0
bathroom                    0
balcony                     0
additionalRoom              0
floorNum                   19
facing                   1104
agePossession               1
nearbyLocations           177
furnishDetails            980
features                  635
dtype: int64

In [37]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)